manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: khoek
      url-base: https://github.com/khoek
  projects:
    - name: zmk
      remote: khoek
      revision: debug
      import: app/west.yml
  self:
    path: config
